from ..utils import CustomCfgNode as CN


DEFAULT_CONFIG = CN(visible=False)

DEFAULT_CONFIG.BASE_FLD = 'results'
DEFAULT_CONFIG.IMAGE_CHANNELS = 3
DEFAULT_CONFIG.NUM_CLASSES = 1
DEFAULT_CONFIG.IMAGE_MEAN = [0.6, 0.6, 0.6]
DEFAULT_CONFIG.IMAGE_STD = [0.2, 0.2, 0.2]
DEFAULT_CONFIG.EXPORT_RENDERGRAPH = True
DEFAULT_CONFIG.EXPORT_ERRORMAP = True
DEFAULT_CONFIG.EXPORT_FEATUREMAP = True
DEFAULT_CONFIG.NUM_FEATUREMAP_SAMPLES = 3
DEFAULT_CONFIG.FEATUREMAP = CN(visible=False)
DEFAULT_CONFIG.FEATUREMAP.fmap_size = 128
DEFAULT_CONFIG.FEATUREMAP.result_width = 4096
DEFAULT_CONFIG.FEATUREMAP.retain_size = True
DEFAULT_CONFIG.FEATUREMAP.colormap = 'COLORMAP_OCEAN'