from ..utils import CustomCfgNode as CN


# LR scheduler
DEFAULT_CONFIG = CN()
# Learning rate scheduler to be used
# could be overwritten by command line argument
DEFAULT_CONFIG.NAME = 'ReduceLROnPlateauWithWarmup'
DEFAULT_CONFIG.VERBOSE = False
DEFAULT_CONFIG.MONITOR = 'valid/epoch/loss'
DEFAULT_CONFIG.MONITOR_MODE = 'min'
DEFAULT_CONFIG.INTERVAL = 'epoch'
DEFAULT_CONFIG.FREQUENCY = 1
# ReduceLROnPlateau parameters
DEFAULT_CONFIG.REDUCEONPLATEAU = CN(visible=False)
DEFAULT_CONFIG.REDUCEONPLATEAU.reduce_factor = 0.2
DEFAULT_CONFIG.REDUCEONPLATEAU.patience = 2
DEFAULT_CONFIG.REDUCEONPLATEAU.threshold = 1e-4
DEFAULT_CONFIG.REDUCEONPLATEAU.threshold_mode = 'rel'
DEFAULT_CONFIG.REDUCEONPLATEAU.cooldown = 0
DEFAULT_CONFIG.REDUCEONPLATEAU.eps = 1e-8
DEFAULT_CONFIG.REDUCEONPLATEAU.min_lr = 5e-6
# Warmup parameters
DEFAULT_CONFIG.WARMUP = CN(visible=False)
DEFAULT_CONFIG.WARMUP.START_FACTOR = 1.0 / 3
DEFAULT_CONFIG.WARMUP.END_FACTOR = 1.0
DEFAULT_CONFIG.WARMUP.WARMUP_EPOCHS = 5
# CyclicLR parameters
DEFAULT_CONFIG.CYCLICLR = CN(visible=False)
DEFAULT_CONFIG.CYCLICLR.base_lr = 5e-4
DEFAULT_CONFIG.CYCLICLR.max_lr = 1e-3
DEFAULT_CONFIG.CYCLICLR.step_size_up = 2000
DEFAULT_CONFIG.CYCLICLR.step_size_down = 2000
DEFAULT_CONFIG.CYCLICLR.mode = 'triangular'
DEFAULT_CONFIG.CYCLICLR.gamma = 1.
DEFAULT_CONFIG.CYCLICLR.cycle_momentum = True
DEFAULT_CONFIG.CYCLICLR.base_momentum = 0.8
DEFAULT_CONFIG.CYCLICLR.max_momentum = 0.9