from ..utils import CustomCfgNode as CN

DEFAULT_CONFIG = CN()
# Loss function to be used for boundary branch
# could be overwritten by command line argument
DEFAULT_CONFIG.ABBR = CN(visible=False)
DEFAULT_CONFIG.ABBR.BCELoss = 'BCE'
DEFAULT_CONFIG.ABBR.BinaryFocalLoss = 'BF'
DEFAULT_CONFIG.ABBR.FocalLoss = 'F'
DEFAULT_CONFIG.ABBR.DiceLoss = 'DC'
DEFAULT_CONFIG.ABBR.SmoothL1NormalizedBCELoss = 'SLN_BCE'
DEFAULT_CONFIG.ABBR.CrossEntropyLoss = 'CE'
DEFAULT_CONFIG.ABBR.KLDivLoss = 'KLD'
DEFAULT_CONFIG.ABBR.MSELoss = 'MSE'
DEFAULT_CONFIG.ABBR.SmoothL1Loss = 'SL1'
DEFAULT_CONFIG.ABBR.HuberLoss = 'HU'

# for backward compatibility
DEFAULT_CONFIG.ABBR.BCEWithLogitsLoss = 'BCE'
DEFAULT_CONFIG.ABBR.BinaryFocalWithLogitsLoss = 'BF'
DEFAULT_CONFIG.ABBR.FocalWithLogitsLoss = 'F'
DEFAULT_CONFIG.ABBR.DiceWithLogitsLoss = 'DC'
DEFAULT_CONFIG.ABBR.SmoothL1NormalizedBCEWithLogitLoss = 'SLN_BCE'

DEFAULT_CONFIG.NAME = ''
DEFAULT_CONFIG.FUNC_NAME = 'Compose'
DEFAULT_CONFIG.WEIGHT = 1.0
DEFAULT_CONFIG.SIDE_OUTPUT_WEIGHTS = [0.5, 0.3, 0.1, 0.1]
DEFAULT_CONFIG.OUTPUT_TYPE = 'logit'

DEFAULT_CONFIG.COMPOSE = CN(visible=False)
DEFAULT_CONFIG.COMPOSE.LIST = [
    'BCEWithLogitsLoss',
    'BinaryFocalWithLogitsLoss',
]
# DEFAULT_CONFIG.COMPOSE.NAME = '0.7BCE+0.3BF'
DEFAULT_CONFIG.COMPOSE.WEIGHT = [0.7, 0.3]

DEFAULT_CONFIG.BCELOSS = CN(visible=False)
DEFAULT_CONFIG.BCELOSS.pos_weight = [1.0]
DEFAULT_CONFIG.BCELOSS.reduction = 'mean'

DEFAULT_CONFIG.CELOSS = CN(visible=False)
DEFAULT_CONFIG.CELOSS.reduction = 'mean'

DEFAULT_CONFIG.KLDIVLOSS = CN(visible=False)
DEFAULT_CONFIG.KLDIVLOSS.reduction = 'batchmean'

DEFAULT_CONFIG.DICELOSS = CN(visible=False)
DEFAULT_CONFIG.DICELOSS.task = 'binary'
DEFAULT_CONFIG.DICELOSS.mode = 'soft'
DEFAULT_CONFIG.DICELOSS.average = 'batch'
DEFAULT_CONFIG.DICELOSS.channel_reduction = 'mean'
DEFAULT_CONFIG.DICELOSS.threshold = 0.5
DEFAULT_CONFIG.DICELOSS.epsilon = 1e-5

DEFAULT_CONFIG.BINARYFOCALLOSS = CN(visible=False)
DEFAULT_CONFIG.BINARYFOCALLOSS.alpha = 0.5
DEFAULT_CONFIG.BINARYFOCALLOSS.gamma = 2.0
DEFAULT_CONFIG.BINARYFOCALLOSS.reduction = 'mean'

DEFAULT_CONFIG.FOCALLOSS = CN(visible=False)
DEFAULT_CONFIG.FOCALLOSS.alpha = 0.5
DEFAULT_CONFIG.FOCALLOSS.gamma = 2.0
DEFAULT_CONFIG.FOCALLOSS.reduction = 'mean'
DEFAULT_CONFIG.FOCALLOSS.balance_index = 0

DEFAULT_CONFIG.MSELOSS = CN(visible=False)
DEFAULT_CONFIG.MSELOSS.reduction = 'mean'

DEFAULT_CONFIG.SMOOTHL1LOSS = CN(visible=False)
DEFAULT_CONFIG.SMOOTHL1LOSS.reduction = 'mean'
DEFAULT_CONFIG.SMOOTHL1LOSS.beta = 0.5

DEFAULT_CONFIG.HUBERLOSS = CN(visible=False)
DEFAULT_CONFIG.HUBERLOSS.reduction = 'mean'
DEFAULT_CONFIG.HUBERLOSS.delta = 0.5

DEFAULT_CONFIG.SLN_BCELOSS = CN(visible=False)
DEFAULT_CONFIG.SLN_BCELOSS.pos_weight = [1.0]
DEFAULT_CONFIG.SLN_BCELOSS.beta = 0.05
DEFAULT_CONFIG.SLN_BCELOSS.label_smoothing = 0.01
DEFAULT_CONFIG.SLN_BCELOSS.reduction = 'mean'