from lib.pytorch_framework.utils import CustomCfgNode as CN


DEFAULT_ENVIRONMENT = CN(visible=False)
DEFAULT_ENVIRONMENT.PROJECT_PATH = ''
DEFAULT_ENVIRONMENT.DATA_BASE_PATH = 'data'
DEFAULT_ENVIRONMENT.RESULT_BASE_PATH = 'results'
DEFAULT_ENVIRONMENT.MLFLOW_BASE_PATH = 'mlflow'